import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-indigo-800 to-primary text-primary-foreground",
          inter.className
        )}
      >
        {children}
      </body>
    </html>
  );
}
